#!/usr/bin/env bash
# Install HAProxy with this configurations
# - Enable management via  init script
# - Distribute request using round-robin algorithm

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend Randommall.tech_backend

backend Randommall.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 20298-web-01 34.207.121.49 check
    server 20298-web-02 54.90.56.41 check
EOT

sudo service haproxy restart

