#!/usr/bin/env bash
# Set Nginx to listen on port 80
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-available/default
sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-available/default
service nginx restart

