#!/usr/bin/env bash
# Script displaying "Best School" 10 times but prints Hi at 9
i=0
while ((a < 10))
do
	((a++))
	if [ $a -eq 4 ]
	then
		echo "bad luck"
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
